### ISSUE TITLE
Documentation and reasoning for SQL query

### ISSUE THREAD

**Issue by ggjx22** [ai-practitioners/time-series-forecasting#19]
To have a README.md that documents:
1. The abbreviations of table names used in the query.

> `train` as `tr`
`stores` as `st`
`holidays_events` as `hols`
`transactions` as `txn`
`oil` as `o`

2. The thought and reasoning processes of arriving at the final state of the query.
3. Step-by-step explanations to be documented.
4. This documentation is stored in `docs/`
5. Document this using MyST Markdown as suggested in #18

**Comment by ggjx22** [comment]
@ellacharmed the documentation is completed. Please have a look when you are ready :)

**Comment by ellacharmed** [comment]
Apologies for being AWOL.

Here's my thoughts after review:

- there's no correlation to an actual physical file as output(s) of this documentation and requires reader to open and see and match the .sql files under src/scripts. Can you link each sql block for that section if the end result in the `.sql` block is to be used? Or just the final query should have an output .sql file? I mean if a user wants to verify this documentation, and see the interim results, they have to copy+paste `.sql` code blocks 6 times, instead of just opening the `.sql` file and running it.
- why create a new file instead of editing/renaming .sql files? Confusing that now have to open and again match which is the one to be used, moving forward i.e. `create_view_full_df.sql` vs `create_view.sql` vs `full_df_as_view.sql`
- in the same spirit, we can clean up the other `.sql` files if not to be used or edited to pull data from the `full_df` view. Especially if want to use `polars` in code to pull the subset records instead of via SQL
- the `{admonitions}`, `{note}` and `{attention}` are not rendered in `github.com`. I think we can use https://github.com/orgs/community/discussions/16925 as the alert boxes now. I tried but according to https://github.com/orgs/community/discussions/16925#discussioncomment-6883420 it does not work in Preview yet, so I can't confirm until I Edit and Push.  
- user is to run script (from [#seventh-merge](https://github.com/ai-practitioners/time-series-forecasting/blob/experiment-polars/docs/sql_query.md#seventh-merge-transactions) ) locally? We no longer using DVC?

**Comment by ggjx22** [comment]
Hello @ellacharmed

I would like to convert the current `sql_query.md` file into a notebook as you've shown [here in your own work](https://ellacharmed.github.io/today-I-learned/0_Jupyter-book/sample%20markdown-notebooks.html). And since github and vscode could not render the effects.

I have been tinkering with a few formats, and settled on the [examples shown here](https://jupyterbook.org/en/stable/reference/cheatsheet.html#figures-and-images), but I'm unable to confirm if they are working as intended. How do you do it?

**Comment by ellacharmed** [comment]
The .md file rendered in github-pages (github**.io**) is different from the markdown flavour in github**.com**. I didn't think of that until I read the {annotations} and {notes} admonitions you were trying to render. Apologies that it slipped my mind when I linked the above github issue page and also during our call.

**Comment by ellacharmed** [comment]
Made following edits:
- all "#" were flagged by linter, so made as 2nd level headings and propagate subsequent heading levels
- replaced all {admonition} with contextually-relevant `> [! ALERTS]`
- tested captions for images using anchors `[Table 1](#table1)` and corresponding `<span id="table1">*Table 1: caption description*</span>`
- do we still want the `{admonition} Query Explanation` as separators?
